name: flask-app

replicaCount: 1

image:
  repository: acrgha.azurecr.io/athulvishnu/flaskapp
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: acr-secret

service:
  name: flask-app-service
  type: LoadBalancer
  port: 80