name: CI/CD Pipeline for Flask App on AKS
on:
  push:
    branches:
      - master
      - feature/*
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Azure login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Helm
        uses: azure/setup-helm@v5.0.0
        with:
          version: v3.12.0
        id: install

      - name: short sha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to ACR
        run: 
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/flaskapp:${{ env.SHORT_SHA }} .
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/flaskapp:${{ env.SHORT_SHA }}

      - name: Set AKS context
        uses: azure/aks-set-context@v5
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
        
      - name: Deploy with Helm
        run: |
          helm upgrade --install flaskapp ./flaskapp-helm \
            --set image.repository=${{ secrets.ACR_NAME }}.azurecr.io/flaskapp \
            --set image.tag=${{ env.SHORT_SHA }} \
            --namespace default
